server:
  port: 11880
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy_code?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: ok
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    cache: false
  resources:
    static-locations: classpath:/static,classpath:/public
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml


logging:
    level:
       com.example.demo.dao : debug

