
server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easy_code?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: ok
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.day.pojo
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: use_flag

logging:
  level:
    com.day.dao : debug

